# Builder image
FROM node:latest AS builder
RUN mkdir /usr/src/app
WORKDIR /usr/src/app
ENV PATH /usr/src/app/node_modules:$PATH
ADD src /usr/src/app/src
ADD .babelrc /usr/src/app
ADD package.json /usr/src/app
ADD package-lock.json /usr/src/app
ADD webpack.config.js /usr/src/app
RUN npm install && npm run build

EXPOSE 8080

CMD ["sh", "-c"]
