version: '3.2'
services:
  dev:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    volumes:
      - ".:/usr/src/app"
      - "pantry-ui-node-modules:/usr/src/app/node_modules"
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
    command: npm run dev

volumes:
  pantry-ui-node-modules:
