#!/bin/sh

function start_dev() {
  docker-compose run dev npm run dev
}

function start_unit_test() {
  docker-compose run dev npm run test
}

#case statement ordered by how commands are listed in ./go help
case "$1" in
  init) shift; init $@
  ;;
  dev) shift; start_dev $@
  ;;
  test) shift; start_unit_test $@
esac;
